version: '3'

networks:
  simple_ai_network:
    name: simple_ai_network
    driver: bridge

services:
  simple-ai-hub:
    build:
      context: .
      dockerfile: Dockerfile
    image: hub-${ID}
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
    container_name: ${HUB}
    restart: always
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    networks:
      - simple_ai_network
