version: '3'

services:
  simple-ai-hub:
    build:
      context: .
      dockerfile: Dockerfile
    image: hub-${ID}
    container_name: ${HUB}
    restart: always
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
